language: ruby
env: RACK_ENV=development
sudo: false
rvm:
- 2.0.0
services:
- docker
before_install:
- docker pull mumuki/mumuki-hspec-worker
- wget https://github.com/mumuki/mulang/releases/download/v0.2.0/mulang
- mv mulang bin/
- chmod +x bin/mulang